from __future__ import annotations

from nerfstudio.plugins.registry_dataparser import DataParserSpecification

from nerf_xray.template_dataparser import TemplateDataParserConfig
from nerf_xray.multi_camera_dataparser import MultiCameraDataParserConfig

XrayDataparser = DataParserSpecification(config=TemplateDataParserConfig())
MultiCameraDataParser = DataParserSpecification(config=MultiCameraDataParserConfig())
